version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15673:15673"  # RabbitMQ Management UI
      - "5673:5673"    # RabbitMQ default port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # Persist RabbitMQ data

volumes:
  rabbitmq-data:  # Declare the named volume to persist data
